---
- name: Get certificate from Let's Encrypt
  tags: certbot
  vars:
    certbot_create_if_missing: True
    certbot_create_method: standalone
    certbot_admin_email: "{{ lets_encrypt_email }}"
    certbot_auto_renew_hour: "4"
    certbot_auto_renew_user: "root"
    certbot_create_standalone_stop_services: False
    certbot_certs:
      - domains: ["{{ inventory_hostname }}"]
  import_role:
    name: geerlingguy.certbot

- name: Generate passwords in 1Password
  dbildungscloud.onepwd.item:
    vault: "{{ proxy_vault }}"
    name: "{{ item.name }}"
    generate_password: "letters,digits,32"
    overwrite: False
  with_items:
    - "{{ proxy_users }}"

- name: Install squid
  apt:
    name: squid-openssl
    update_cache: true
  notify: Reload squid

- name: Set configuration
  template:
    src: "templates/squid.conf.j2"
    dest: "/etc/squid/squid.conf"
  notify: Reload squid

- name: Install passlib (required for htpasswd module)
  pip: 
    name: passlib

- name: Set/remove allowed users for proxy
  vars:
    project_stage: "{{ project }}-{{ stage }}"
    allowed: "{{ (item.everywhere is defined and item.everywhere == True) or (item.project_stage is defined and project_stage in item.project_stage) }}"
  htpasswd:
    path: /etc/squid/htpasswd
    name: "{{ item.name }}"
    password: "{{ lookup('dbildungscloud.onepwd.onepwd', secret_name=item.name, vault=proxy_vault, field='password', session_shorthand='ansible-run') }}"
    state: "{{ 'present' if allowed else 'absent'}}"
  when: item.name is defined
  with_items:
    - "{{ proxy_users }}"
