---
- name: Reload squid
  ansible.builtin.service:
    name: squid
    enabled: true
    state: reloaded
- name: Reload fail2ban
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: reloaded