---
- name: Restore Ingress
  kubernetes.core.k8s:
    state: patched
    kubeconfig: "{{ kubeconfig }}"
    kind: Ingress
    name: "{{ maintenance_target_ingress }}"
    namespace: "{{ maintenance_namespace }}"
    definition:
      spec: "{{ lookup('file', '/tmp/{{ maintenance_page_release_name }}-ingress.yml') | from_yaml }}"

- name: Delete maintenance Nginx Helm chart
  kubernetes.core.helm:
    name: "{{ maintenance_page_release_name }}"
    state: absent
    wait: true
    kubeconfig: "{{ kubeconfig }}"
    release_namespace: "{{ maintenance_namespace }}"
